---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.names.msname }}-{{ .Values.names.fename }}
  namespace: {{ .Values.nsname }} 
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: {{ .Values.names.msname }} 
      layer: {{ .Values.names.fename }}
  replicas: 2
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata:
      labels:
        app: {{ .Values.names.msname }}
        layer: {{ .Values.names.fename }}
    spec:
      containers:
      - name: mycart-frontend-container
        image: vasakris/mycart-frontend:6.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "400Mi"
          requests:
            cpu: "0.2"
            memory: "200Mi"
        env:
          - name: BACKENDLB
            value: backendapi
