---
version: "3.7"
services:
  mycart-frontend:
    build:
      context: ./frontend
    image: vasakris/mycart-frontend:5.0
    depends_on:
      - mycart-backend
    environment:
      BACKENDLB: mycart-backend
    ports:
      - "9000:80"
    volumes:
      - type: volume
        source: mycart-frontend-varlog
        target: /var/log
  mycart-frontend-logs:
    build:
      context: ./awslogs
    image: vasakris/mycart-frontend-logs:5.0
    depends_on:
      - mycart-frontend
    volumes:
      - type: volume
        source: mycart-frontend-varlog
        target: /mnt/log
        read_only: true
  mycart-backend:
    build:
      context: ./backend
    image: vasakris/mycart-backend:5.0
    volumes:
      - type: volume
        source: mycart-backend-varlog
        target: /var/log
  mycart-backend-logs:
    build:
      context: ./awslogs
    image: vasakris/mycart-backend-logs:5.0
    depends_on:
      - mycart-backend   
    volumes:
      - type: volume
        source: mycart-backend-varlog
        target: /mnt/log
        read_only: true
volumes:
  mycart-frontend-varlog:
  mycart-backend-varlog: